trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs: 
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        repository: 'michalpicheta / testproject'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'