trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
    - name: tf_folder
      value: $(System.DafaultWorkingDirectory)/cwiczenia\spterraform

steps:
    - script: |
        docker run --tty --volume @(tf_folder):/tf bridgecrew/checkov --directory /tf --compact
      displayName: Run test